/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import type { SqlColorTokenType } from "./contracts.js";

/** Lexical terminals that carry a fixed classification regardless of their syntactic position. */
export const literalTokenTypes: ReadonlyMap<string, SqlColorTokenType> = new Map([
    ["LineComment", "comment"],
    ["BlockComment", "comment"],
    ["StringLiteral", "string"],
    ["BinaryLiteral", "number"],
    ["MoneyLiteral", "number"],
    ["FloatLiteral", "number"],
    ["DecimalLiteral", "number"],
    ["IntegerLiteral", "number"],
]);

/**
 * Arithmetic, bitwise, comparison, and assignment terminals. Pure punctuation is excluded so
 * commas, semicolons, parentheses, and name dots keep the editor's syntactic coloring.
 */
export const operatorTokenKinds: ReadonlySet<string> = new Set([
    "Plus",
    "Minus",
    "Star",
    "Slash",
    "PercentSign",
    "Ampersand",
    "Pipe",
    "Caret",
    "Tilde",
    "Equal",
    "PlusEqual",
    "MinusEqual",
    "StarEqual",
    "EqualStar",
    "SlashEqual",
    "PercentEqual",
    "AmpersandEqual",
    "PipeEqual",
    "CaretEqual",
    "ShiftLeft",
    "ShiftRight",
    "DoublePipe",
    "ConcatEqual",
    "NotEqual",
    "LessThanOrEqual",
    "GreaterThanOrEqual",
    "LessThan",
    "GreaterThan",
]);

/** Pre-ANSI outer-join comparisons, which SQL Server removed after compatibility level 90. */
export const deprecatedOperatorTokenKinds: ReadonlySet<string> = new Set([
    "StarEqual",
    "EqualStar",
]);

export const identifierTokenKinds: ReadonlySet<string> = new Set([
    "Identifier",
    "BracketedIdentifier",
    "DoubleQuotedIdentifier",
    "TempIdentifier",
    "PseudoColumn",
]);

export const quotedIdentifierTokenKinds: ReadonlySet<string> = new Set([
    "BracketedIdentifier",
    "DoubleQuotedIdentifier",
]);

export interface ObjectNameStatementRole {
    readonly type: SqlColorTokenType;
    readonly definition: boolean;
    readonly declaration: boolean;
}

/**
 * Statements whose direct name children denote the object the statement acts on. Statements naming
 * two different objects — index, statistics, and trigger targets — are handled explicitly instead,
 * because position rather than statement kind selects their roles.
 */
export const objectNameStatements: ReadonlyMap<string, ObjectNameStatementRole> = new Map([
    ["CreateTableStatement", { type: "table", definition: true, declaration: true }],
    ["AlterTableStatement", { type: "table", definition: true, declaration: false }],
    ["DropTableStatement", { type: "table", definition: false, declaration: false }],
    ["TruncateTableStatement", { type: "table", definition: false, declaration: false }],
    ["CreateViewStatement", { type: "view", definition: true, declaration: true }],
    ["AlterViewStatement", { type: "view", definition: true, declaration: false }],
    ["CreateMaterializedViewStatement", { type: "view", definition: true, declaration: true }],
    ["AlterMaterializedViewStatement", { type: "view", definition: true, declaration: false }],
    ["DropViewStatement", { type: "view", definition: false, declaration: false }],
    ["CreateProcedureStatement", { type: "procedure", definition: true, declaration: true }],
    ["AlterProcedureStatement", { type: "procedure", definition: true, declaration: false }],
    ["DropProcedureStatement", { type: "procedure", definition: false, declaration: false }],
    ["CreateFunctionStatement", { type: "function", definition: true, declaration: true }],
    ["AlterFunctionStatement", { type: "function", definition: true, declaration: false }],
    ["DropFunctionStatement", { type: "function", definition: false, declaration: false }],
    ["CreateTriggerStatement", { type: "procedure", definition: true, declaration: true }],
    ["AlterTriggerStatement", { type: "procedure", definition: true, declaration: false }],
    ["CreateTypeStatement", { type: "type", definition: true, declaration: true }],
    ["DropTypeStatement", { type: "type", definition: false, declaration: false }],
    ["CreateSchemaStatement", { type: "schema", definition: true, declaration: true }],
    ["AlterSchemaStatement", { type: "schema", definition: true, declaration: false }],
    ["DropSchemaStatement", { type: "schema", definition: false, declaration: false }],
    ["CreateDatabaseStatement", { type: "database", definition: true, declaration: true }],
    ["AlterDatabaseStatement", { type: "database", definition: true, declaration: false }],
    ["DropDatabaseStatement", { type: "database", definition: false, declaration: false }],
]);

/** Statements that name an index or statistics object first and the table it belongs to second. */
export const indexOwnerStatements: ReadonlySet<string> = new Set([
    "CreateIndexStatement",
    "CreateJsonIndexStatement",
    "CreateVectorIndexStatement",
    "CreateSemanticIndexStatement",
    "AlterIndexStatement",
    "CreateStatisticsStatement",
]);

/**
 * Built-in Transact-SQL routines, which no catalog lookup returns. The list stays limited to
 * unqualified names SQL Server ships in every database. A user routine of the same name still
 * binds through the catalog, and the bound classification replaces this one.
 */
export const builtInRoutineNames: ReadonlySet<string> = new Set(
    [
        "ABS",
        "ACOS",
        "APP_NAME",
        "ASCII",
        "ASIN",
        "ATAN",
        "ATN2",
        "AVG",
        "CEILING",
        "CHAR",
        "CHARINDEX",
        "CHECKSUM",
        "CHOOSE",
        "COALESCE",
        "COL_LENGTH",
        "COL_NAME",
        "CONCAT",
        "CONCAT_WS",
        "COS",
        "COT",
        "COUNT",
        "COUNT_BIG",
        "CUME_DIST",
        "DATALENGTH",
        "DATEADD",
        "DATEDIFF",
        "DATEDIFF_BIG",
        "DATEFROMPARTS",
        "DATENAME",
        "DATEPART",
        "DATETRUNC",
        "DAY",
        "DB_ID",
        "DB_NAME",
        "DEGREES",
        "DENSE_RANK",
        "DIFFERENCE",
        "EOMONTH",
        "ERROR_LINE",
        "ERROR_MESSAGE",
        "ERROR_NUMBER",
        "ERROR_PROCEDURE",
        "ERROR_SEVERITY",
        "ERROR_STATE",
        "EXP",
        "FIRST_VALUE",
        "FLOOR",
        "FORMAT",
        "FORMATMESSAGE",
        "GETDATE",
        "GETUTCDATE",
        "GREATEST",
        "GROUPING",
        "GROUPING_ID",
        "HAS_PERMS_BY_NAME",
        "HOST_NAME",
        "IDENT_CURRENT",
        "IIF",
        "INDEX_COL",
        "ISDATE",
        "ISJSON",
        "ISNULL",
        "ISNUMERIC",
        "JSON_ARRAY",
        "JSON_ARRAYAGG",
        "JSON_MODIFY",
        "JSON_OBJECT",
        "JSON_OBJECTAGG",
        "JSON_PATH_EXISTS",
        "JSON_QUERY",
        "JSON_VALUE",
        "LAG",
        "LAST_VALUE",
        "LEAD",
        "LEAST",
        "LEN",
        "LOG",
        "LOG10",
        "LOWER",
        "LTRIM",
        "MAX",
        "MIN",
        "MONTH",
        "NCHAR",
        "NEWID",
        "NEWSEQUENTIALID",
        "NTILE",
        "NULLIF",
        "OBJECT_DEFINITION",
        "OBJECT_ID",
        "OBJECT_NAME",
        "OBJECT_SCHEMA_NAME",
        "OPENJSON",
        "PARSENAME",
        "PATINDEX",
        "PERCENTILE_CONT",
        "PERCENTILE_DISC",
        "PERCENT_RANK",
        "PI",
        "POWER",
        "QUOTENAME",
        "RADIANS",
        "RAND",
        "RANK",
        "REPLACE",
        "REPLICATE",
        "REVERSE",
        "ROUND",
        "ROW_NUMBER",
        "RTRIM",
        "SCHEMA_ID",
        "SCHEMA_NAME",
        "SCOPE_IDENTITY",
        "SERVERPROPERTY",
        "SIGN",
        "SIN",
        "SOUNDEX",
        "SPACE",
        "SQRT",
        "SQUARE",
        "STDEV",
        "STDEVP",
        "STR",
        "STRING_AGG",
        "STRING_ESCAPE",
        "STRING_SPLIT",
        "STUFF",
        "SUBSTRING",
        "SUM",
        "SUSER_NAME",
        "SUSER_SNAME",
        "SWITCHOFFSET",
        "SYSDATETIME",
        "SYSDATETIMEOFFSET",
        "SYSUTCDATETIME",
        "TAN",
        "TODATETIMEOFFSET",
        "TRIM",
        "TYPE_ID",
        "TYPE_NAME",
        "UNICODE",
        "UPPER",
        "USER_ID",
        "USER_NAME",
        "VAR",
        "VARP",
        "VECTOR_DISTANCE",
        "YEAR",
    ].map((name) => name.toLowerCase()),
);
