import { WebSocketEvent } from './../../src/js/interfaces';

const batch: WebSocketEvent = {
  type: 'batch',
  data: {
  'executionElapsed': '00:00:00.1879820',
  'executionEnd': '2016-11-10T17:39:27.9893860-08:00',
  'executionStart': '2016-11-10T17:39:27.8014040-08:00',
  'hasError': false,
  'id': 0,
  'selection': {
    'endColumn': 1,
    'endLine': 5,
    'startColumn': 0,
    'startLine': 3
  },
  'messages': [
    {
      'time': '2016-11-10T17:39:27.9773300-08:00',
      'message': '(115 rows affected)'
    }
  ],
  'resultSetSummaries': [
    {
      'id': 0,
      'rowCount': 10,
      'columnInfo': [
        {
          'isBytes': false,
          'isChars': true,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'name',
          'allowDBundefined': false,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 0,
          'columnSize': 128,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': false,
          'isUnique': false,
          'numericPrecision': 255,
          'numericScale': 255,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'nvarchar',
          'baseSchemaName': undefined
        },
        {
          'isBytes': false,
          'isChars': false,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'object_id',
          'allowDBundefined': false,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 1,
          'columnSize': 4,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': false,
          'isUnique': false,
          'numericPrecision': 10,
          'numericScale': 255,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'int',
          'baseSchemaName': undefined
        },
        {
          'isBytes': false,
          'isChars': false,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'principal_id',
          'allowDBundefined': true,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 2,
          'columnSize': 4,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': false,
          'isUnique': false,
          'numericPrecision': 10,
          'numericScale': 255,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'int',
          'baseSchemaName': undefined
        },
        {
          'isBytes': false,
          'isChars': false,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'schema_id',
          'allowDBundefined': false,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 3,
          'columnSize': 4,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': false,
          'isUnique': false,
          'numericPrecision': 10,
          'numericScale': 255,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'int',
          'baseSchemaName': undefined
        },
        {
          'isBytes': false,
          'isChars': false,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'parent_object_id',
          'allowDBundefined': false,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 4,
          'columnSize': 4,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': false,
          'isUnique': false,
          'numericPrecision': 10,
          'numericScale': 255,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'int',
          'baseSchemaName': undefined
        },
        {
          'isBytes': false,
          'isChars': false,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'type',
          'allowDBundefined': true,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 5,
          'columnSize': 2,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': true,
          'isUnique': false,
          'numericPrecision': 255,
          'numericScale': 255,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'char',
          'baseSchemaName': undefined
        },
        {
          'isBytes': false,
          'isChars': true,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'type_desc',
          'allowDBundefined': true,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 6,
          'columnSize': 60,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': false,
          'isUnique': false,
          'numericPrecision': 255,
          'numericScale': 255,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'nvarchar',
          'baseSchemaName': undefined
        },
        {
          'isBytes': false,
          'isChars': false,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'create_date',
          'allowDBundefined': false,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 7,
          'columnSize': 8,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': false,
          'isUnique': false,
          'numericPrecision': 23,
          'numericScale': 3,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.DateTime, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'datetime',
          'baseSchemaName': undefined
        },
        {
          'isBytes': false,
          'isChars': false,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'modify_date',
          'allowDBundefined': false,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 8,
          'columnSize': 8,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': false,
          'isUnique': false,
          'numericPrecision': 23,
          'numericScale': 3,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.DateTime, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'datetime',
          'baseSchemaName': undefined
        },
        {
          'isBytes': false,
          'isChars': false,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'is_ms_shipped',
          'allowDBundefined': false,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 9,
          'columnSize': 1,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': true,
          'isUnique': false,
          'numericPrecision': 255,
          'numericScale': 255,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'bit',
          'baseSchemaName': undefined
        },
        {
          'isBytes': false,
          'isChars': false,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'is_published',
          'allowDBundefined': false,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 10,
          'columnSize': 1,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': true,
          'isUnique': false,
          'numericPrecision': 255,
          'numericScale': 255,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'bit',
          'baseSchemaName': undefined
        },
        {
          'isBytes': false,
          'isChars': false,
          'isLong': false,
          'isSqlVariant': false,
          'isUdt': false,
          'isXml': false,
          'isJson': false,
          'columnName': 'is_schema_published',
          'allowDBundefined': false,
          'baseCatalogName': undefined,
          'baseColumnName': undefined,
          'baseServerName': undefined,
          'baseTableName': undefined,
          'columnOrdinal': 11,
          'columnSize': 1,
          'isAliased': undefined,
          'isAutoIncrement': false,
          'isExpression': undefined,
          'isHidden': undefined,
          'isIdentity': false,
          'isKey': undefined,
          'isReadOnly': true,
          'isUnique': false,
          'numericPrecision': 255,
          'numericScale': 255,
          'udtAssemblyQualifiedName': undefined,
          'dataType': 'System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e',
          'dataTypeName': 'bit',
          'baseSchemaName': undefined
        }
      ]
    }
  ]}
};

export default batch;
