language: node_js
node_js:
    - "6.9.1"
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
install:
  - npm install
  - npm run vscode:prepublish
before_script:
    - npm install -g gulp-cli
    - npm install -g
script:
    - gulp install
    - gulp build
    - "node ./node_modules/vscode/bin/test"
    - "./node_modules/.bin/karma start --single-run --browsers Chrome"