sudo: required
language: node_js
node_js:
  - "6.9.1"
before_install:
  - sudo apt-get install libxss1 libappindicator1 libindicator7 libfontconfig1 libstdc++6 fonts-liberation lsb-base
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
before_script:
  - npm install -g gulp-cli
script:
  - gulp install
  - gulp build
  - "./node_modules/.bin/karma start"