sudo: required
language: node_js
node_js:
  - "6.9.1"
before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - sudo apt-get update
  - sudo apt-get intall google-chrome-stable
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
before_script:
  - npm install -g gulp-cli
script:
  - gulp install
  - gulp build
  - "./node_modules/.bin/karma start"