sudo: required
dist: trusty

language: node_js
node_js:
  - "6.9.1"

os:
  - linux
  - osx

before_install:
  #- wget http://security.ubuntu.com/ubuntu/pool/universe/c/chromium-browser/chromium-browser_53.0.2785.143-0ubuntu0.14.04.1.1145_amd64.deb
  #- sudo dpkg -i chromium-browser*.deb
  #- export CHROME_BIN=/usr/bin/google-chrome
  - export CHROME_BIN=chromium-browser
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xclip; fi
  - npm install -g npm
install:
  - npm install -g --silent gulp-cli
  - npm install -g --silent xvfb-maybe
  - npm install
  - gulp install
script:
  - gulp build
  - gulp cover:enableconfig
  - xvfb-maybe ./node_modules/.bin/karma start
  - xvfb-maybe node ./node_modules/vscode/bin/test
  - gulp cover:combine
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./node_modules/.bin/coveralls < coverage/lcov.info; fi
