sudo: required
language: node_js
node_js:
  - "6.9.1"
before_install:
  - sudo apt-get install google-chrome-stable=53.0.2785.143-0
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
before_script:
  - npm install -g gulp-cli
script:
  - gulp install
  - gulp build
  - "./node_modules/.bin/karma start"