environment:
  nodejs_version: "6.9.1"

  # Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # show versions
  - npm --version
  - node --version
  - lsb_release -a
  # install modules
  - npm install
  - npm install -g gulp-cli
  - gulp install

test_script:
  - gulp build

build: off