name: Bug Report / Feature Request - MSSQL Extension for VS Code
description: File a bug report to help us improve the MSSQL extension.
title: "[Bug]: "
labels: ["bug", "Triage: Needed", "User-filed"]
assignees: []

body:
  # Introductory message to thank the user and set expectations
  - type: markdown
    attributes:
      value: |
        ## Thank you for taking the time to report a bug!
        Please provide as much detail as possible (screenshots, screen recordings, logs) to help us reproduce and fix the issue.

  # Section for describing the issue
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly explain what you expected to happen and what actually happened.
      placeholder: |
        Expected the MSSQL extension to...
        But what actually happened was...
        Paste or drag and drop screenshots or recordings that show the bug.
    validations:
      required: true

  # Section for providing steps to reproduce the issue
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: Describe the steps that led to the issue.
      placeholder: |
        1. Connected to database...
        2. Executed query...
        3. Viewed results...
        4. Observed unexpected output or behavior...
    validations:
      required: true

  # Section for selecting affected areas
  - type: checkboxes
    id: affected-area
    attributes:
      label: Affected Area
      description: Select all the areas where you encountered issues.
      options:
        - label: Connection dialog
        - label: Query editor
        - label: IntelliSense/auto-completion
        - label: Query results panel
        - label: Object Explorer
        - label: Table Designer
        - label: Schema Compare
        - label: Schema Designer
        - label: Query Plan Visualizer
        - label: Other (please describe below)

  - type: textarea
    id: other-affected-area
    attributes:
      label: If you selected "Other", please describe the affected area
      description: Only fill this if you selected "Other" above.
      placeholder: Describe the affected area here...
    validations:
      required: false

  # Section for providing environment details
  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Add versions and environment details below.
      placeholder: |
        • VS Code Version:
        • MSSQL Extension Version:
        • Operating System:
        • SQL Server Version/Edition:
        • Connection Type (SQL database in Fabric, Azure SQL, SQL Server, etc.):
    validations:
      required: true

  # Section for confirming issue search and willingness to work on the issue
  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmation
      options:
        - label: I have searched existing issues and couldn't find a match
          required: true
        - label: I want to work on this issue

  # Closing message to thank the user
  - type: markdown
    attributes:
      value: "Thank you for reporting this issue! We'll get back to you as soon as possible. 🙌"