blank_issues_enabled: false
contact_links:
  - name: MSSQL extension for VS Code - Community Support
    url: https://aka.ms/vscode-mssql-discussions/
    about: Please ask and answer questions here.
