name: Add comment to issue or PR with tags
on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read markdown file and add comment
        run: |
          # Get the label name and create the filename dynamically
          FILE_NAME=$(echo "${{ github.event.label.name }}" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]').md
          FILE_PATH=".github/actions/issue-tag-comment/$FILE_NAME"

          # Check if the event is for an issue or a PR and get the number
          if [ "${{ github.event_name }}" == "issues" ]; then
            NUMBER="${{ github.event.issue.number }}"
            COMMENT_COMMAND="gh issue comment"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            NUMBER="${{ github.event.pull_request.number }}"
            COMMENT_COMMAND="gh pr comment"
          fi

          # Check if the file exists and read its content
          if [ -f "$FILE_PATH" ]; then
            COMMENT_BODY=$(cat "$FILE_PATH")
            $COMMENT_COMMAND "$NUMBER" --body "$COMMENT_BODY"
          else
            echo "File $FILE_PATH not found."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

