/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// Curated T-SQL keyword registry. Changes require public product-documentation evidence and tests;
// see GRAMMAR_PROVENANCE.md. This is maintained source rather than imported parser output.

export interface ReservedKeywordMetadata {
    readonly token: string;
    readonly minimumCompatibility: number;
}

export interface ContextualKeywordUse {
    readonly context: string;
    readonly token: string;
}

export const reservedKeywordMetadata = Object.freeze({
    add: { token: "_ADD", minimumCompatibility: 60 },
    all: { token: "_ALL", minimumCompatibility: 42 },
    alter: { token: "_ALTER", minimumCompatibility: 42 },
    and: { token: "_AND", minimumCompatibility: 42 },
    any: { token: "_ANY", minimumCompatibility: 42 },
    approx: { token: "_APPROX", minimumCompatibility: 170 },
    approximate: { token: "_APPROXIMATE", minimumCompatibility: 170 },
    as: { token: "_AS", minimumCompatibility: 42 },
    asc: { token: "_ASC", minimumCompatibility: 42 },
    authorization: { token: "_AUTHORIZATION", minimumCompatibility: 65 },
    backup: { token: "_DUMP", minimumCompatibility: 70 },
    begin: { token: "_BEGIN", minimumCompatibility: 42 },
    between: { token: "_BETWEEN", minimumCompatibility: 42 },
    break: { token: "_BREAK", minimumCompatibility: 42 },
    browse: { token: "_BROWSE", minimumCompatibility: 42 },
    bulk: { token: "_BULK", minimumCompatibility: 42 },
    by: { token: "_BY", minimumCompatibility: 42 },
    cascade: { token: "_CASCADE", minimumCompatibility: 65 },
    case: { token: "_CASE", minimumCompatibility: 60 },
    check: { token: "_CHECK", minimumCompatibility: 42 },
    checkpoint: { token: "_CHECKPOINT", minimumCompatibility: 42 },
    close: { token: "_CLOSE", minimumCompatibility: 60 },
    clustered: { token: "_CLUSTERED", minimumCompatibility: 42 },
    coalesce: { token: "_COALESCE", minimumCompatibility: 60 },
    collate: { token: "_COLLATE", minimumCompatibility: 80 },
    column: { token: "_COLUMN", minimumCompatibility: 70 },
    commit: { token: "_COMMIT", minimumCompatibility: 42 },
    compute: { token: "_COMPUTE", minimumCompatibility: 42 },
    constraint: { token: "_CONSTRAINT", minimumCompatibility: 60 },
    contains: { token: "_CONTAINS", minimumCompatibility: 70 },
    containstable: { token: "_CONTAINSTABLE", minimumCompatibility: 70 },
    continue: { token: "_CONTINUE", minimumCompatibility: 42 },
    convert: { token: "_CONVERT", minimumCompatibility: 42 },
    create: { token: "_CREATE", minimumCompatibility: 42 },
    cross: { token: "_CROSS", minimumCompatibility: 65 },
    current: { token: "_CURRENT", minimumCompatibility: 60 },
    current_date: { token: "_CURRENT_DATE", minimumCompatibility: 60 },
    current_time: { token: "_CURRENT_TIME", minimumCompatibility: 60 },
    current_timestamp: { token: "_CURRENT_TIMESTAMP", minimumCompatibility: 60 },
    current_user: { token: "_CURRENT_USER", minimumCompatibility: 60 },
    cursor: { token: "_CURSOR", minimumCompatibility: 60 },
    database: { token: "_DATABASE", minimumCompatibility: 42 },
    dbcc: { token: "_DBCC", minimumCompatibility: 42 },
    deallocate: { token: "_DEALLOCATE", minimumCompatibility: 60 },
    declare: { token: "_DECLARE", minimumCompatibility: 42 },
    default: { token: "_DEFAULT", minimumCompatibility: 42 },
    delete: { token: "_DELETE", minimumCompatibility: 42 },
    deny: { token: "_DENY", minimumCompatibility: 60 },
    desc: { token: "_DESC", minimumCompatibility: 42 },
    distinct: { token: "_DISTINCT", minimumCompatibility: 42 },
    distributed: { token: "_DISTRIBUTED", minimumCompatibility: 65 },
    double: { token: "_DOUBLE", minimumCompatibility: 60 },
    drop: { token: "_DROP", minimumCompatibility: 42 },
    else: { token: "_ELSE", minimumCompatibility: 42 },
    end: { token: "_END", minimumCompatibility: 42 },
    errlvl: { token: "_ERRLVL", minimumCompatibility: 42 },
    escape: { token: "_ESCAPE", minimumCompatibility: 65 },
    except: { token: "_EXCEPT", minimumCompatibility: 42 },
    exec: { token: "_EXECUTE", minimumCompatibility: 42 },
    execute: { token: "_EXECUTE", minimumCompatibility: 42 },
    exists: { token: "_EXISTS", minimumCompatibility: 42 },
    exit: { token: "_EXIT", minimumCompatibility: 42 },
    external: { token: "_EXTERNAL", minimumCompatibility: 90 },
    fetch: { token: "_FETCH", minimumCompatibility: 60 },
    file: { token: "_FILE", minimumCompatibility: 42 },
    fillfactor: { token: "_FILLFACTOR", minimumCompatibility: 42 },
    for: { token: "_FOR", minimumCompatibility: 42 },
    foreign: { token: "_FOREIGN", minimumCompatibility: 60 },
    freetext: { token: "_FREETEXT", minimumCompatibility: 70 },
    freetexttable: { token: "_FREETEXTTABLE", minimumCompatibility: 70 },
    from: { token: "_FROM", minimumCompatibility: 42 },
    full: { token: "_FULL", minimumCompatibility: 65 },
    function: { token: "_FUNCTION", minimumCompatibility: 80 },
    goto: { token: "_GOTO", minimumCompatibility: 42 },
    grant: { token: "_GRANT", minimumCompatibility: 42 },
    group: { token: "_GROUP", minimumCompatibility: 42 },
    having: { token: "_HAVING", minimumCompatibility: 42 },
    holdlock: { token: "_HOLDLOCK", minimumCompatibility: 42 },
    identity: { token: "_IDENTITY", minimumCompatibility: 60 },
    identity_insert: { token: "_IDENTITY_INSERT", minimumCompatibility: 60 },
    identitycol: { token: "_IDENTITYCOL", minimumCompatibility: 60 },
    if: { token: "_IF", minimumCompatibility: 42 },
    in: { token: "_IN", minimumCompatibility: 42 },
    index: { token: "_INDEX", minimumCompatibility: 42 },
    inner: { token: "_INNER", minimumCompatibility: 65 },
    insert: { token: "_INSERT", minimumCompatibility: 42 },
    intersect: { token: "_INTERSECT", minimumCompatibility: 42 },
    into: { token: "_INTO", minimumCompatibility: 42 },
    is: { token: "_IS", minimumCompatibility: 42 },
    join: { token: "_JOIN", minimumCompatibility: 65 },
    key: { token: "_KEY", minimumCompatibility: 60 },
    kill: { token: "_KILL", minimumCompatibility: 42 },
    left: { token: "_LEFT", minimumCompatibility: 65 },
    like: { token: "_LIKE", minimumCompatibility: 42 },
    lineno: { token: "_LINENO", minimumCompatibility: 42 },
    merge: { token: "_MERGE", minimumCompatibility: 100 },
    national: { token: "_NATIONAL", minimumCompatibility: 70 },
    nocheck: { token: "_NOCHECK", minimumCompatibility: 60 },
    nonclustered: { token: "_NONCLUSTERED", minimumCompatibility: 42 },
    not: { token: "_NOT", minimumCompatibility: 42 },
    null: { token: "_NULL", minimumCompatibility: 42 },
    nullif: { token: "_NULLIF", minimumCompatibility: 60 },
    of: { token: "_OF", minimumCompatibility: 60 },
    off: { token: "_OFF", minimumCompatibility: 42 },
    offsets: { token: "_OFFSETS", minimumCompatibility: 42 },
    on: { token: "_ON", minimumCompatibility: 42 },
    open: { token: "_OPEN", minimumCompatibility: 60 },
    opendatasource: { token: "_OPENDATASOURCE", minimumCompatibility: 70 },
    openquery: { token: "_OPENQUERY", minimumCompatibility: 70 },
    openrowset: { token: "_OPENROWSET", minimumCompatibility: 70 },
    openxml: { token: "_OPENXML", minimumCompatibility: 80 },
    option: { token: "_OPTION", minimumCompatibility: 60 },
    or: { token: "_OR", minimumCompatibility: 42 },
    order: { token: "_ORDER", minimumCompatibility: 42 },
    outer: { token: "_OUTER", minimumCompatibility: 65 },
    over: { token: "_OVER", minimumCompatibility: 42 },
    percent: { token: "_PERCENT", minimumCompatibility: 70 },
    pivot: { token: "_PIVOT", minimumCompatibility: 90 },
    plan: { token: "_PLAN", minimumCompatibility: 42 },
    primary: { token: "_PRIMARY", minimumCompatibility: 60 },
    print: { token: "_PRINT", minimumCompatibility: 42 },
    proc: { token: "_PROCEDURE", minimumCompatibility: 42 },
    procedure: { token: "_PROCEDURE", minimumCompatibility: 42 },
    public: { token: "_PUBLIC", minimumCompatibility: 42 },
    raiserror: { token: "_RAISERROR", minimumCompatibility: 42 },
    read: { token: "_READ", minimumCompatibility: 60 },
    readtext: { token: "_READTEXT", minimumCompatibility: 42 },
    reconfigure: { token: "_RECONFIGURE", minimumCompatibility: 42 },
    references: { token: "_REFERENCES", minimumCompatibility: 60 },
    regexp_like: { token: "_REGEXP_LIKE", minimumCompatibility: 170 },
    replication: { token: "_REPLICATION", minimumCompatibility: 60 },
    restore: { token: "_LOAD", minimumCompatibility: 70 },
    restrict: { token: "_RESTRICT", minimumCompatibility: 65 },
    return: { token: "_RETURN", minimumCompatibility: 42 },
    revert: { token: "_REVERT", minimumCompatibility: 90 },
    revoke: { token: "_REVOKE", minimumCompatibility: 42 },
    right: { token: "_RIGHT", minimumCompatibility: 65 },
    rollback: { token: "_ROLLBACK", minimumCompatibility: 42 },
    rowcount: { token: "_ROWCOUNT", minimumCompatibility: 42 },
    rowguidcol: { token: "_ROWGUIDCOL", minimumCompatibility: 70 },
    rule: { token: "_RULE", minimumCompatibility: 42 },
    save: { token: "_SAVE", minimumCompatibility: 42 },
    schema: { token: "_SCHEMA", minimumCompatibility: 65 },
    select: { token: "_SELECT", minimumCompatibility: 42 },
    semantickeyphrasetable: { token: "_SEMANTICKEYPHRASETABLE", minimumCompatibility: 110 },
    semanticsimilaritydetailstable: {
        token: "_SEMANTICSIMILARITYDETAILSTABLE",
        minimumCompatibility: 110,
    },
    semanticsimilaritytable: { token: "_SEMANTICSIMILARITYTABLE", minimumCompatibility: 110 },
    session_user: { token: "_SESSION_USER", minimumCompatibility: 60 },
    set: { token: "_SET", minimumCompatibility: 42 },
    setuser: { token: "_SETUSER", minimumCompatibility: 42 },
    shutdown: { token: "_SHUTDOWN", minimumCompatibility: 42 },
    some: { token: "_ANY", minimumCompatibility: 60 },
    statistics: { token: "_STATISTICS", minimumCompatibility: 42 },
    system_user: { token: "_SYSTEM_USER", minimumCompatibility: 60 },
    table: { token: "_TABLE", minimumCompatibility: 42 },
    tablesample: { token: "_TABLESAMPLE", minimumCompatibility: 90 },
    textsize: { token: "_TEXTSIZE", minimumCompatibility: 42 },
    then: { token: "_THEN", minimumCompatibility: 60 },
    to: { token: "_TO", minimumCompatibility: 42 },
    top: { token: "_TOP", minimumCompatibility: 70 },
    tran: { token: "_TRANSACTION", minimumCompatibility: 42 },
    transaction: { token: "_TRANSACTION", minimumCompatibility: 42 },
    trigger: { token: "_TRIGGER", minimumCompatibility: 42 },
    truncate: { token: "_TRUNCATE", minimumCompatibility: 42 },
    try_convert: { token: "_TRY_CONVERT", minimumCompatibility: 110 },
    tsequal: { token: "_TSEQUAL", minimumCompatibility: 42 },
    union: { token: "_UNION", minimumCompatibility: 42 },
    unique: { token: "_UNIQUE", minimumCompatibility: 42 },
    unpivot: { token: "_UNPIVOT", minimumCompatibility: 90 },
    update: { token: "_UPDATE", minimumCompatibility: 42 },
    updatetext: { token: "_UPDATETEXT", minimumCompatibility: 60 },
    use: { token: "_USEDB", minimumCompatibility: 42 },
    user: { token: "_USER", minimumCompatibility: 60 },
    values: { token: "_VALUES", minimumCompatibility: 42 },
    varying: { token: "_VARYING", minimumCompatibility: 60 },
    view: { token: "_VIEW", minimumCompatibility: 42 },
    waitfor: { token: "_WAITFOR", minimumCompatibility: 42 },
    when: { token: "_WHEN", minimumCompatibility: 60 },
    where: { token: "_WHERE", minimumCompatibility: 42 },
    wherecurrent: { token: "_WHERE_CURRENT", minimumCompatibility: 42 },
    while: { token: "_WHILE", minimumCompatibility: 42 },
    with: { token: "_WITH", minimumCompatibility: 42 },
    writetext: { token: "_WRITETEXT", minimumCompatibility: 42 },
} satisfies Readonly<Record<string, ReservedKeywordMetadata>>);

export const contextualKeywordMetadata = Object.freeze({
    "<default>": [
        { context: "after_begin", token: "_ID" },
        { context: "after_with", token: "_s_AW_ID" },
        { context: "ag_replica_option", token: "_s_AG_ROLE_AGNOSTIC_OPTION" },
        { context: "alter_db_opt", token: "_s_ALTDBOPT_OTHER" },
        { context: "create_db_opt", token: "_s_CREATEDBOPT_OTHER" },
        { context: "dump_opt", token: "_s_DUMPOPT_OTHER" },
        { context: "ind_options", token: "_s_IO_ONOFFOPTION" },
        { context: "load_opt", token: "_s_LOADOPT_OTHER" },
    ],
    abort: [{ context: "ind_actions", token: "_s_IA_ABORT" }],
    abort_after_wait: [{ context: "tab_lock_opt", token: "_s_TABLOCKOPT_ABORT_AFTER_WAIT" }],
    absent: [{ context: "json_func_opt", token: "_s_JFO_ABSENT" }],
    accelerated_database_recovery: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_ACCELERATED_DATABASE_RECOVERY" },
    ],
    after: [{ context: "security_policy", token: "_s_SP_AFTER" }],
    aggregate: [{ context: "create_drop_alter", token: "_s_CDA_AGGREGATE" }],
    algorithm: [
        { context: "col_encryption_or_master_key", token: "_s_CEMK_ALGORITHM" },
        { context: "dump_compression_opt", token: "_s_DUMPOPT_COMPRESSION_ALGORITHM" },
        { context: "dump_encryption_opt", token: "_s_DUMPOPT_ENCRYPTION_ALGORITHM" },
    ],
    allow_connections: [{ context: "geodr_opt", token: "_s_GEODR_CONNOPT" }],
    allow_encrypted_value_modifications: [
        { context: "create_user_with", token: "_s_CUW_PROPERTY" },
    ],
    api_format: [
        { context: "alter_externalmodel_with", token: "_s_AEM_APIFORMAT" },
        { context: "create_externalmodel_with", token: "_s_CEM_APIFORMAT" },
    ],
    append_only: [{ context: "create_table_with_ledger_opt", token: "_s_CTWL_APPEND_ONLY" }],
    application: [{ context: "create_drop_alter", token: "_s_CDA_APPLICATION" }],
    application_log: [{ context: "audit_target_type", token: "_s_ET_APPLICATION_LOG" }],
    assembly: [
        { context: "create_drop_alter", token: "_s_CDA_ASSEMBLY" },
        { context: "opteventnotifobjecton", token: "_c_ASSEMBLY" },
    ],
    asymmetric: [
        { context: "create_drop_alter", token: "_s_CDA_ASYMMETRIC" },
        { context: "dump_encryption_opt", token: "_s_DUMPOPT_ENCRYPTION_ASYMMETRIC" },
        { context: "optdumptypes", token: "_c_ASYMMETRIC" },
        { context: "optloadtypes", token: "_c_ASYMMETRIC" },
        { context: "optopenclosetypes", token: "_c_ASYMMETRIC" },
    ],
    async: [{ context: "geodr_opt", token: "_s_GEODR_ASYNC_FAILOVER" }],
    atomic: [{ context: "after_begin", token: "_s_AB_ATOMIC" }],
    audit: [
        { context: "alter_server_type", token: "_s_altserv_AUDIT" },
        { context: "create_drop_alter", token: "_s_CDA_AUDIT" },
    ],
    auto: [{ context: "auto_tuning_database_tuning_mode_opt", token: "_s_ALTDBOPT_ATDBTM_auto" }],
    auto_create_statistics: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_AUTO_CRT_STATS" }],
    automatic_index_compaction: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_AUTOMATIC_INDEX_COMPACTION" },
    ],
    automatic_tuning: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_AUTO_TUNING" }],
    availability: [{ context: "create_drop_alter", token: "_s_CDA_AVAILABILITY" }],
    backup_storage_redundancy: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_BACKUPSTORAGEREDUNDANCY" },
        { context: "create_db_opt", token: "_s_CREATEDBOPT_BACKUPSTORAGEREDUNDANCY" },
        { context: "db_copy_opt", token: "_s_DB_COPY_BACKUP_STORAGE_REDUNDANCY" },
        { context: "geodr_opt", token: "_s_GEODR_BACKUPSTORAGEREDUNDANCY" },
    ],
    before: [{ context: "security_policy", token: "_s_SP_BEFORE" }],
    blob_storage: [{ context: "create_externaldatasource_with", token: "_s_CEDS_BLOBSTORAGE" }],
    block: [{ context: "security_policy", token: "_s_SP_BLOCK" }],
    broker: [{ context: "create_drop_alter", token: "_s_CDA_BROKER" }],
    bucket_count: [{ context: "ind_options", token: "_s_IO_BUCKETCOUNT" }],
    buffer: [
        {
            context: "alter_server_config_set",
            token: "_s_altserv_config_set_BUFFER_POOL_EXTENSION",
        },
    ],
    build: [{ context: "view_snapshot", token: "_s_SBUILD" }],
    build_replica: [{ context: "view_snapshot", token: "_s_SBUILD_REPLICA" }],
    cache: [{ context: "sequence_options", token: "_s_seq_CACHE" }],
    catalog: [{ context: "fulltext_search", token: "_s_FTS_CATALOG" }],
    catch: [{ context: "after_end", token: "_s_AE_CATCH" }],
    certificate: [
        { context: "create_drop_alter", token: "_s_CDA_CERT" },
        { context: "dump_encryption_opt", token: "_s_DUMPOPT_ENCRYPTION_CERTIFICATE" },
        { context: "optdumptypes", token: "_c_CERT" },
    ],
    change_tracking: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_CHANGE_TRACKING" },
        { context: "alttab_enable_disable", token: "_s_ALTTAB_EN_CHANGE_TRACKING" },
        { context: "fulltext_search", token: "_s_FTS_CHANGE_TRACKING" },
    ],
    change_tracking_context: [{ context: "after_with", token: "_s_AW_CHANGE_TRACKING_CONTEXT" }],
    chunk_size: [{ context: "gen_chunks_opt", token: "_s_GC_CHUNK_SIZE" }],
    chunk_type: [{ context: "gen_chunks_opt", token: "_s_GC_CHUNK_TYPE" }],
    chunk_using: [{ context: "semantic_index_col_options", token: "_s_SI_CHUNK_USING" }],
    classification: [
        { context: "add", token: "_s_ADD_CLASSIFICATION" },
        { context: "create_drop_alter", token: "_s_CDA_CLASSIFICATION" },
    ],
    cleanup_policy: [{ context: "query_store_opt", token: "_s_QDS_CLEANUP_POLICY" }],
    column_encryption_key: [
        { context: "col_encryption_or_master_key", token: "_s_CEMK_COL_ENCRYPTION_KEY" },
    ],
    column_master_key: [
        { context: "col_encryption_or_master_key", token: "_s_CEMK_COL_MASTER_KEY" },
    ],
    column_set: [
        { context: "col_def_opt", token: "_s_COLDEFOPT_COLUMN_SET" },
        { context: "opt_storage_id", token: "_s_OSI_COLUMN_SET" },
    ],
    columnstore: [
        { context: "create_drop_alter", token: "_s_CDA_COLUMNSTORE" },
        { context: "in_inline_index_syntax", token: "_s_IIIS_COLUMNSTORE" },
    ],
    compression: [{ context: "dump_opt", token: "_s_DUMPOPT_COMPRESSION" }],
    compression_delay: [{ context: "ind_options", token: "_s_IO_COMPRESSION_DELAY" }],
    configuration: [{ context: "alter_server_type", token: "_s_altserv_CONFIG" }],
    connection_options: [
        { context: "create_externaldatasource_with", token: "_s_CEDS_CONNECTIONOPTIONS" },
    ],
    containment: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_CONTAINEDDB" }],
    content: [
        { context: "external_language_file_spec_opt", token: "_s_ELFS_CONTENT" },
        { context: "external_library_file_spec_opt", token: "_s_ELIBFS_CONTENT" },
    ],
    context: [
        {
            context: "alter_server_config_set_hadr_cluster",
            token: "_s_altserv_config_set_hadr_cluster_CONTEXT",
        },
    ],
    contract: [{ context: "create_drop_alter", token: "_s_CDA_CONTRACT" }],
    conversation: [
        { context: "after_end", token: "_s_AE_CONVERSATION" },
        { context: "optbegintypes", token: "_c_CONVERSATION" },
    ],
    copy: [{ context: "create_db_type", token: "_s_CREATEDB_COPY" }],
    counter: [
        { context: "add", token: "_s_ADD_COUNTER" },
        { context: "create_drop_alter", token: "_s_CDA_COUNTER" },
    ],
    cpu: [
        { context: "affinity_type", token: "_s_aff_CPU" },
        { context: "external_pool_affinity_type", token: "_s_epaff_CPU" },
    ],
    credential: [
        { context: "alter_externaldatasource_with", token: "_s_AEDS_CREDENTIAL" },
        { context: "alter_externalmodel_with", token: "_s_AEM_CREDENTIAL" },
        { context: "create_drop_alter", token: "_s_CDA_CREDENTIAL" },
        { context: "create_externaldatasource_with", token: "_s_CEDS_CREDENTIAL" },
        { context: "create_externalmodel_with", token: "_s_CEM_CREDENTIAL" },
        { context: "remote_data_archive_opt", token: "_s_REMOTE_DATA_ARCHIVE_DB_OPT_CREDENTIAL" },
    ],
    cryptographic: [{ context: "create_drop_alter", token: "_s_CDA_CRYPTOGRAPHIC" }],
    cube: [{ context: "optgroupby", token: "_c_CUBE" }],
    custom: [
        { context: "auto_tuning_database_tuning_mode_opt", token: "_s_ALTDBOPT_ATDBTM_custom" },
    ],
    cycle: [{ context: "sequence_options", token: "_s_seq_CYCLE" }],
    data: [{ context: "external_type", token: "_s_ET_DATASOURCE" }],
    data_compression: [
        { context: "create_externalfileformat_with", token: "_s_CEFF_DATA_COMPRESSION" },
        { context: "create_tab_with_opt", token: "_s_CTW_DATA_COMPRESSION" },
        { context: "ind_options", token: "_s_IO_DATACOMPRESSION" },
    ],
    data_consistency_check: [
        { context: "system_versioning_opt", token: "_s_SV_DATA_CONSISTENCY_CHECK" },
    ],
    data_deletion: [
        { context: "create_tab_with_opt", token: "_s_CTW_DATA_DELETION" },
        { context: "tab_opt_name", token: "_s_TABOPTNAME_DATA_DELETION" },
    ],
    data_flush_interval_seconds: [{ context: "query_store_opt", token: "_s_QDS_FLUSH_INTERVAL" }],
    data_retention: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_DATA_RETENTION" }],
    data_source: [
        { context: "create_externalstream_with", token: "_s_CES_DATA_SOURCE" },
        { context: "create_externaltable_with", token: "_s_CET_DATASOURCE" },
    ],
    database_name: [
        { context: "alter_externaldatasource_with", token: "_s_AEDS_DATABASENAME" },
        { context: "create_externaldatasource_with", token: "_s_CEDS_DATABASENAME" },
        { context: "geodr_opt", token: "_s_GEODR_DATABASENAME" },
    ],
    date_format: [{ context: "create_externalfileformat_with", token: "_s_CEFF_DATEFORMAT" }],
    day: [{ context: "create_tab_with_data_deletion_opt", token: "_s_DD_DAY" }],
    default_language: [
        { context: "alter_user_with", token: "_s_AUW_PROPERTY" },
        { context: "create_user_with", token: "_s_CUW_PROPERTY" },
    ],
    default_schema: [
        { context: "alter_user_with", token: "_s_AUW_PROPERTY" },
        { context: "create_user_with", token: "_s_CUW_PROPERTY" },
    ],
    delayed_durability: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_DELAYED_DURABILITY" }],
    delimitedtext: [{ context: "create_externalfileformat_with", token: "_s_CEFF_DELIMITEDTEXT" }],
    desired_state: [{ context: "query_store_opt", token: "_s_QDS_DESIRED_STATE" }],
    diagnostics: [
        { context: "alter_server_config_set", token: "_s_altserv_config_set_DIAGNOSTICS" },
    ],
    dialog: [{ context: "optbegintypes", token: "_c_DIALOG" }],
    directory_name: [
        { context: "filestream_db_opt", token: "_s_FSD_DIRECTORY_NAME" },
        {
            context: "persistent_log_buffer_opt",
            token: "_s_PERSISTENT_LOG_BUFFER_OPT_DIRECTORY_NAME",
        },
    ],
    disable: [
        { context: "alttab_actions", token: "_s_ALTTAB_DISABLE_ENABLE" },
        { context: "ind_actions", token: "_s_IA_DISABLE" },
        { context: "optstmtstarters", token: "_c_DISABLE" },
    ],
    distribution: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_DIST_POLICY" },
        { context: "alter_db_opt", token: "_s_CTW_DISTRIBUTION" },
        { context: "create_externaltable_with", token: "_s_CET_DISTRIBUTION" },
        { context: "ind_options", token: "_s_IO_DISTRIBUTION" },
    ],
    drop_existing: [{ context: "semantic_index_with_options", token: "_s_SIW_DROP_EXISTING" }],
    durability: [{ context: "create_tab_with_opt", token: "_s_CTW_DURABILITY" }],
    edge: [{ context: "graph_id_or_filetable", token: "_s_EDGE_TYPE" }],
    embeddings: [
        { context: "alter_externalmodel_with", token: "_s_AEM_EMBED" },
        { context: "create_externalmodel_with", token: "_s_CEM_EMBED" },
    ],
    enable: [
        { context: "alttab_actions", token: "_s_ALTTAB_DISABLE_ENABLE" },
        { context: "optstmtstarters", token: "_c_ENABLE" },
    ],
    enable_chunk_set_id: [{ context: "gen_chunks_opt", token: "_s_GC_CHUNK_SET_ID" }],
    enclave_computations: [
        { context: "col_encryption_or_master_key", token: "_s_CEMK_ENCLAVE_SUPPORT" },
    ],
    encoding: [{ context: "create_externalfileformat_with", token: "_s_CEFF_ENCODING" }],
    encrypted: [{ context: "col_def_opt", token: "_s_COLDEFOPT_ENCRYPTED" }],
    encrypted_value: [{ context: "col_encryption_or_master_key", token: "_s_CEMK_ENCRYPTED_VAL" }],
    encryption: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_ENCRYPTION" },
        { context: "col_encryption_or_master_key", token: "_s_CEMK_ENCRYPTION" },
        { context: "dump_opt", token: "_s_DUMPOPT_ENCRYPTION" },
    ],
    encryption_type: [
        { context: "col_encryption_or_master_key", token: "_s_CEMK_ENCRYPTION_TYPE" },
    ],
    endpoint: [{ context: "create_drop_alter", token: "_s_CDA_ENDPOINT" }],
    environment_variables: [
        { context: "external_language_file_spec_opt", token: "_s_ELFS_ENVIRONMENT_VARIABLES" },
    ],
    event: [{ context: "create_drop_alter", token: "_s_CDA_EVENT" }],
    external_model: [{ context: "semantic_index_with_options", token: "_s_SIW_EXTERNAL_MODEL" }],
    external_monitor: [{ context: "audit_target_type", token: "_s_ET_EXTERNAL_MONITOR" }],
    failover: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_failover" },
        { context: "alter_server_config_set", token: "_s_altserv_config_set_FAILOVER" },
    ],
    false: [{ context: "create_externalfileformat_with", token: "_s_CEFF_FALSE" }],
    federated: [{ context: "create_tab_opt", token: "_s_CTO_FEDERATED" }],
    federated_service_account: [
        {
            context: "remote_data_archive_opt",
            token: "_s_REMOTE_DATA_ARCHIVE_DB_OPT_FEDERATED_SERVICE_ACCOUNT",
        },
    ],
    field_terminator: [
        { context: "create_externalfileformat_with", token: "_s_CEFF_FIELDTERMINATOR" },
    ],
    file: [{ context: "external_type", token: "_s_ET_FILEFORMAT" }],
    file_format: [
        { context: "create_externalstream_with", token: "_s_CES_FILE_FORMAT" },
        { context: "create_externaltable_with", token: "_s_CET_FILEFORMAT" },
    ],
    file_name: [{ context: "external_language_file_spec_opt", token: "_s_ELFS_FILE_NAME" }],
    filegroup: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_filegroup" }],
    filestream: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_FILESTREAM" },
        { context: "col_def_opt", token: "_s_COLDEFOPT_FILESTREAM" },
        { context: "create_db_opt", token: "_s_CREATEDBOPT_FILESTREAM" },
        { context: "load_opt", token: "_s_LOADOPT_FILESTREAM" },
    ],
    filestream_on: [
        { context: "create_tab_opt", token: "_s_CTO_FILESTREAM_ON" },
        { context: "in_inline_index_syntax", token: "_s_IIIS_FILESTREAM_ON" },
        { context: "tab_opt_name", token: "_s_TABOPTNAME_FILESTREAM_ON" },
    ],
    filetable: [{ context: "graph_id_or_filetable", token: "_s_FILETABLE" }],
    filetable_collate_filename: [
        { context: "create_tab_with_opt", token: "_s_CTW_FFT_COLLATE_FILENAME" },
    ],
    filetable_directory: [
        { context: "create_tab_with_opt", token: "_s_CTW_FFT_FILETABLE_DIRECTORY" },
        { context: "tab_opt_name", token: "_s_TABOPTNAME_FILETABLE_DIRECTORY" },
    ],
    filetable_fullpath_unique_constraint_name: [
        { context: "create_tab_with_opt", token: "_s_CTW_FFT_FULLPATH_UNIQUE_CONSTRAINT_NAME" },
    ],
    filetable_namespace: [
        { context: "alttab_enable_disable", token: "_s_ALTTAB_EN_FILETABLE_NAMESPACE" },
    ],
    filetable_primary_key_constraint_name: [
        { context: "create_tab_with_opt", token: "_s_CTW_FFT_PRIMARY_KEY_CONSTRAINT_NAME" },
    ],
    filetable_streamid_unique_constraint_name: [
        { context: "create_tab_with_opt", token: "_s_CTW_FFT_STREAMID_UNIQUE_CONSTRAINT_NAME" },
    ],
    filter: [{ context: "security_policy", token: "_s_SP_FILTER" }],
    filter_column: [{ context: "create_tab_with_data_deletion_opt", token: "_s_DD_FILTER_COLUMN" }],
    first_row: [{ context: "create_externalfileformat_with", token: "_s_CEFF_FIRSTROW" }],
    fixed: [{ context: "gen_chunks_chunk_type_opt", token: "_s_GC_FIXED" }],
    flush_interval_seconds: [
        { context: "query_store_opt", token: "_s_QDS_FLUSH_INTERVAL_SECONDS" },
    ],
    force_failover_allow_data_loss: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_force_failover" },
    ],
    format: [{ context: "external_type", token: "_s_ET_FORMAT" }],
    format_options: [
        { context: "create_externalfileformat_with", token: "_s_CEFF_FORMAT_OPTIONS" },
    ],
    format_type: [{ context: "create_externalfileformat_with", token: "_s_CEFF_FORMAT_TYPE" }],
    fulltext: [{ context: "create_drop_alter", token: "_s_CDA_FULLTEXT" }],
    fulltext_stoplist: [{ context: "semantic_index_with_options", token: "_s_SIW_FT_STOPLIST" }],
    generated: [{ context: "col_def_opt", token: "_s_COLDEFOPT_COLUMN_GENERATED" }],
    get: [{ context: "optstmtstarters", token: "_c_GET" }],
    governor: [{ context: "create_drop_alter", token: "_s_CDA_GOVERNOR" }],
    hadoop: [{ context: "create_externaldatasource_with", token: "_s_CEDS_HADOOP" }],
    hadr: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_HADR" },
        { context: "alter_server_config_set", token: "_s_altserv_config_set_HADR" },
    ],
    hardening: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_HARDENING" }],
    hash: [
        { context: "create_externaltable_with", token: "_s_CET_HASH" },
        { context: "in_inline_index_syntax", token: "_s_IIIS_HASH" },
    ],
    heap: [{ context: "create_tab_with_opt", token: "_s_CTW_HEAP" }],
    hidden: [
        { context: "col_add_drop_opt", token: "_s_COLADDROPOPT_HIDDEN" },
        { context: "col_def_opt", token: "_s_COLDEFOPT_HIDDEN" },
    ],
    history_retention_period: [
        { context: "system_versioning_opt", token: "_s_SV_HISTORY_RETENTION_PERIOD" },
    ],
    history_table: [{ context: "system_versioning_opt", token: "_s_SV_HISTORY_TABLE" }],
    hour: [{ context: "create_tab_with_data_deletion_opt", token: "_s_DD_HOUR" }],
    increment: [{ context: "sequence_options", token: "_s_seq_INCREMENT" }],
    infinite: [{ context: "create_tab_with_data_deletion_opt", token: "_s_DD_INFINITE" }],
    inherit: [
        { context: "auto_tuning_database_tuning_mode_opt", token: "_s_ALTDBOPT_ATDBTM_inherit" },
    ],
    input_options: [{ context: "create_externalstream_with", token: "_s_CES_INPUT_OPTIONS" }],
    interval_length_minutes: [{ context: "query_store_opt", token: "_s_QDS_INTERVAL_LENGTH" }],
    job_tracker_location: [
        { context: "create_externaldatasource_with", token: "_s_CEDS_JOBTRACKERLOCATION" },
    ],
    json: [
        { context: "create_drop_alter", token: "_s_CDA_JSON" },
        { context: "create_externalfileformat_with", token: "_s_CEFF_JSON" },
    ],
    key_path: [{ context: "col_encryption_or_master_key", token: "_s_CEMK_PATH" }],
    key_store_provider_name: [
        { context: "col_encryption_or_master_key", token: "_s_CEMK_PROVIDER_NAME" },
    ],
    key_store_type: [{ context: "col_encryption_or_master_key", token: "_s_CEMK_KEYSTORETYPE" }],
    l: [
        { context: "ind_options", token: "_s_IO_VECTORINDEXL" },
        { context: "vector_search_opt", token: "_s_VS_L" },
    ],
    language: [
        { context: "external_type", token: "_s_ET_LANGUAGE" },
        { context: "semantic_index_col_options", token: "_s_SI_LANGUAGE" },
    ],
    ledger: [{ context: "create_tab_with_opt", token: "_s_CTW_LEDGER" }],
    ledger_view: [{ context: "create_table_with_ledger_opt", token: "_s_CTWL_LEDGER_VIEW" }],
    legacy_cardinality_estimation: [
        { context: "db_scoped_config_opt", token: "_s_DBSC_ON_OFF_OPTION" },
    ],
    level: [{ context: "dump_compression_opt", token: "_s_DUMPOPT_COMPRESSION_LEVEL" }],
    library: [{ context: "external_type", token: "_s_ET_LIBRARY" }],
    list: [{ context: "fts_property", token: "_s_FP_LIST" }],
    local_runtime_path: [
        { context: "alter_externalmodel_with", token: "_s_AEM_LOCALRUNTIMEPATH" },
        { context: "create_externalmodel_with", token: "_s_CEM_LOCALRUNTIMEPATH" },
    ],
    location: [
        { context: "alter_externaldatasource_with", token: "_s_AEDS_LOCATION" },
        { context: "alter_externalmodel_with", token: "_s_AEM_LOCATION" },
        { context: "create_externaldatasource_with", token: "_s_CEDS_LOCATION" },
        { context: "create_externalmodel_with", token: "_s_CEM_LOCATION" },
        { context: "create_externalstream_with", token: "_s_CES_LOCATION" },
        { context: "create_externaltable_with", token: "_s_CET_LOCATION" },
        { context: "create_tab_with_opt", token: "_s_CTW_LOCATION" },
    ],
    lock_escalation: [{ context: "tab_opt_name", token: "_s_TABOPTNAME_LOCK_ESCALATION" }],
    log: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_log" },
        { context: "optdumptypes", token: "_c_LOG" },
        { context: "optloadtypes", token: "_c_LOG" },
    ],
    login: [
        { context: "alter_user_with", token: "_s_AUW_PROPERTY" },
        { context: "create_drop_alter", token: "_s_CDA_LOGIN" },
    ],
    m: [
        { context: "ind_options", token: "_s_IO_VECTORINDEXM" },
        { context: "vector_search_opt", token: "_s_VS_M" },
    ],
    masked: [
        { context: "col_add_drop_opt", token: "_s_COLADDROPOPT_MASKED" },
        { context: "col_def_opt", token: "_s_COLDEFOPT_MASKED" },
    ],
    master: [
        { context: "col_encryption_or_master_key", token: "_s_CEMK_MASTER" },
        { context: "create_drop_alter", token: "_s_CDA_MASTER" },
        { context: "optdumptypes", token: "_c_MASTER" },
        { context: "optloadtypes", token: "_c_MASTER" },
        { context: "optopenclosetypes", token: "_c_MASTER" },
    ],
    max_duration: [
        { context: "ind_options", token: "_s_IO_MAX_DURATION" },
        { context: "tab_lock_opt", token: "_s_TABLOCKOPT_MAX_DURATION" },
    ],
    max_files: [
        {
            context: "alter_server_config_set_diag_log",
            token: "_s_altserv_config_set_diaglog_MAX_FILES",
        },
    ],
    max_plans_per_query: [{ context: "query_store_opt", token: "_s_QDS_MAX_PLANS_PER_QUERY" }],
    max_size: [
        {
            context: "alter_server_config_set_diag_log",
            token: "_s_altserv_config_set_diaglog_MAX_SIZE",
        },
    ],
    max_storage_size_mb: [{ context: "query_store_opt", token: "_s_QDS_MAX_SIZE_MB" }],
    maxdop: [
        { context: "db_scoped_config_opt", token: "_s_DBSC_MAX_DOP" },
        { context: "ind_options", token: "_s_IO_MAXDOP" },
        { context: "semantic_index_with_options", token: "_s_SIW_MAXDOP" },
    ],
    maxlength: [{ context: "opt_sxi_path_option", token: "_s_SXI_MAXLENGTH" }],
    maxvalue: [{ context: "sequence_options", token: "_s_seq_MAXVALUE" }],
    mds_log: [{ context: "audit_target_type", token: "_s_ET_MDS_LOG" }],
    memory_optimized: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_MEMORY_OPTIMIZED" },
        { context: "create_tab_with_opt", token: "_s_CTW_MEMORY_OPTIMIZED" },
    ],
    merge: [{ context: "optstmtstarters", token: "_MERGE" }],
    message: [{ context: "create_drop_alter", token: "_s_CDA_MESSAGE" }],
    metric: [
        { context: "ind_options", token: "_s_IO_VECTORINDEXMETRIC" },
        { context: "vector_search_opt", token: "_s_VS_METRIC" },
    ],
    minute: [{ context: "create_tab_with_data_deletion_opt", token: "_s_DD_MINUTE" }],
    minvalue: [{ context: "sequence_options", token: "_s_seq_MINVALUE" }],
    model: [
        { context: "alter_externalmodel_with", token: "_s_AEM_MODELNAME" },
        { context: "create_externalmodel_with", token: "_s_CEM_MODELNAME" },
        { context: "external_type", token: "_s_ET_MODEL" },
        { context: "gen_embeddings_opt", token: "_s_EMBEDDINGS_MODEL" },
    ],
    model_type: [
        { context: "alter_externalmodel_with", token: "_s_AEM_MODELTYPE" },
        { context: "create_externalmodel_with", token: "_s_CEM_MODELTYPE" },
    ],
    modify: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_modify" }],
    month: [{ context: "create_tab_with_data_deletion_opt", token: "_s_DD_MONTH" }],
    move: [{ context: "optstmtstarters", token: "_c_MOVE" }],
    name: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_name" },
        { context: "alter_user_with", token: "_s_AUW_PROPERTY" },
    ],
    no: [
        { context: "fulltext_search", token: "_s_FTS_NO" },
        { context: "sequence_options", token: "_s_seq_NO" },
    ],
    node: [{ context: "graph_id_or_filetable", token: "_s_NODE_TYPE" }],
    non_transacted_access: [
        { context: "filestream_db_opt", token: "_s_FSD_NON_TRANSACTED_ACCESS" },
    ],
    notification: [{ context: "create_drop_alter", token: "_s_CDA_NOTIFICATION" }],
    numanode: [
        { context: "affinity_type", token: "_s_aff_NUMA" },
        { context: "external_pool_affinity_type", token: "_s_epaff_NUMA" },
        { context: "pool_affinity_type", token: "_s_paff_NUMA" },
    ],
    object_id: [{ context: "create_user_with", token: "_s_CUW_PROPERTY" }],
    object_name: [{ context: "create_externaltable_with", token: "_s_CET_REMOTEOBJECTNAME" }],
    off: [
        { context: "alter_server_config_set_diag_log", token: "_s_altserv_config_set_diaglog_OFF" },
    ],
    on: [
        { context: "alter_server_config_set_diag_log", token: "_s_altserv_config_set_diaglog_ON" },
    ],
    online: [{ context: "ind_options", token: "_s_IO_ONLINE" }],
    operation_mode: [{ context: "query_store_opt", token: "_s_QDS_OPERATION_MODE" }],
    operation_type_column_name: [
        {
            context: "create_table_with_ledger_opt",
            token: "_s_CTWL_LV_OPERATION_TYPE_ID_COLUMN_NAME",
        },
    ],
    operation_type_desc_column_name: [
        {
            context: "create_table_with_ledger_opt",
            token: "_s_CTWL_LV_OPERATION_TYPE_DESC_COLUMN_NAME",
        },
    ],
    optimize_for_array_search: [
        { context: "ind_options", token: "_s_IO_JSONINDEX_OPTIMIZEFORARRAYSEARCH" },
    ],
    optimized_locking: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_OPTIMIZED_LOCKING" }],
    orc: [{ context: "create_externalfileformat_with", token: "_s_CEFF_ORC" }],
    output_options: [{ context: "create_externalstream_with", token: "_s_CES_OUTPUT_OPTIONS" }],
    overlap: [
        { context: "gen_chunks_opt", token: "_s_GC_OVERLAP" },
        { context: "semantic_index_col_chunk_options", token: "_s_SIC_OVERLAP" },
    ],
    parameter_sniffing: [{ context: "db_scoped_config_opt", token: "_s_DBSC_ON_OFF_OPTION" }],
    parameters: [
        { context: "alter_externalmodel_with", token: "_s_AEM_DEFAULT" },
        { context: "create_externalmodel_with", token: "_s_CEM_DEFAULT" },
        { context: "external_language_file_spec_opt", token: "_s_ELFS_PARAMETERS" },
        { context: "gen_embeddings_opt", token: "_s_EMBEDDINGS_PARAMETERS" },
    ],
    parquet: [{ context: "create_externalfileformat_with", token: "_s_CEFF_PARQUET" }],
    partition: [
        { context: "alter_db_opt", token: "_s_CTW_PARTITION" },
        { context: "create_drop_alter", token: "_s_CDA_PARTITION" },
        { context: "over_clause", token: "_s_PARTITION" },
    ],
    password: [
        { context: "alter_user_with", token: "_s_AUW_PASSWORD" },
        { context: "create_user_with", token: "_s_CUW_PASSWORD" },
    ],
    path: [
        {
            context: "alter_server_config_set_diag_log",
            token: "_s_altserv_config_set_diaglog_PATH",
        },
    ],
    pause: [{ context: "ind_actions", token: "_s_IA_PAUSE" }],
    percentage: [{ context: "create_externaltable_with", token: "_s_CET_PERCENTAGE" }],
    perform_cutover: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_perform_cutover" }],
    persisted: [{ context: "col_add_drop_opt", token: "_s_COLADDROPOPT_PERSISTED" }],
    persistent_log_buffer: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_PERSISTENT_LOG_BUFFER" },
        { context: "create_db_opt", token: "_s_CREATEDBOPT_PERSISTENT_LOG_BUFFER" },
    ],
    persistent_version_store_filegroup: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_PERSISTENT_VERSION_STORE_FILEGROUP" },
    ],
    platform: [
        { context: "alter_external_language_opt", token: "_s_ALTELOPT_PLATFORM" },
        { context: "alter_external_library_opt", token: "_s_ALTELIBOPT_PLATFORM" },
        { context: "external_language_file_spec_opt", token: "_s_ELFS_PLATFORM" },
        { context: "external_library_file_spec_opt", token: "_s_ELIBFS_PLATFORM" },
    ],
    policy: [{ context: "create_drop_alter", token: "_s_CDA_POLICY" }],
    pool: [
        { context: "create_drop_alter", token: "_s_CDA_POOL" },
        { context: "external_type", token: "_s_ET_POOL" },
    ],
    population: [{ context: "fulltext_search", token: "_s_FTS_POPULATION" }],
    predicate: [{ context: "security_policy", token: "_s_SP_PREDICATE" }],
    primary_role: [{ context: "ag_replica_option", token: "_s_AG_ROLE_SPECIFIC_OPTION" }],
    process: [{ context: "alter_server_config_set", token: "_s_altserv_config_set_PROCESS" }],
    property: [{ context: "fts_property", token: "_s_FP_PROPERTY" }],
    property_description: [{ context: "after_fts_with", token: "_s_AFW_PROPERTY_DESCRIPTION" }],
    property_int_id: [{ context: "after_fts_with", token: "_s_AFW_PROPERTY_INT_ID" }],
    property_set_guid: [{ context: "after_fts_with", token: "_s_AFW_PROPERTY_SET_GUID" }],
    pushdown: [
        { context: "alter_externaldatasource_with", token: "_s_AEDS_PUSHDOWN" },
        { context: "create_externaldatasource_with", token: "_s_CEDS_PUSHDOWN" },
    ],
    query_capture_mode: [{ context: "query_store_opt", token: "_s_QDS_CAPTURE_MODE" }],
    query_optimizer_hotfixes: [{ context: "db_scoped_config_opt", token: "_s_DBSC_ON_OFF_OPTION" }],
    query_store: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_QUERY_STORE" }],
    queue: [
        { context: "create_drop_alter", token: "_s_CDA_QUEUE" },
        { context: "opteventnotifobjecton", token: "_c_QUEUE" },
    ],
    r: [{ context: "ind_options", token: "_s_IO_VECTORINDEXR" }],
    rcfile: [{ context: "create_externalfileformat_with", token: "_s_CEFF_RCFILE" }],
    rdbms: [{ context: "create_externaldatasource_with", token: "_s_CEDS_RDBMS" }],
    rebuild: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_rebuild" },
        { context: "alttab_actions", token: "_s_ALTTAB_REBUILD" },
        { context: "ind_actions", token: "_s_IA_REBUILD" },
    ],
    receive: [{ context: "optstmtstarters", token: "_c_RECEIVE" }],
    recompile: [{ context: "after_with_exec_option", token: "_s_AWEO_RECOMPILE" }],
    refresh_mode: [{ context: "view_snapshot", token: "_s_SREFRESH_MODE" }],
    reject_sample_value: [
        { context: "create_externaltable_with", token: "_s_CET_REJECTSAMPLEVALUE" },
    ],
    reject_type: [{ context: "create_externaltable_with", token: "_s_CET_REJECTTYPE" }],
    reject_value: [{ context: "create_externaltable_with", token: "_s_CET_REJECTVALUE" }],
    rejected_row_location: [
        { context: "create_externaltable_with", token: "_s_CET_REJECTEDROWLOCATION" },
    ],
    remote: [{ context: "create_drop_alter", token: "_s_CDA_REMOTE" }],
    remote_data_archive: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_REMOTE_DATA_ARCHIVE" },
        { context: "create_tab_with_opt", token: "_s_CTW_REMOTE_DATA_ARCHIVE" },
        { context: "tab_opt_name", token: "_s_TABOPTNAME_REMOTE_DATA_ARCHIVE" },
    ],
    remove: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_remove" },
        { context: "alter_external_language_opt", token: "_s_ALTELOPT_REMOVE" },
        { context: "alter_external_library_opt", token: "_s_ALTELIBOPT_REMOVE" },
    ],
    reorganize: [{ context: "ind_actions", token: "_s_IA_REORGANIZE" }],
    replace: [{ context: "geodr_opt", token: "_s_GEODR_REPLACE" }],
    replicated: [{ context: "create_externaltable_with", token: "_s_CET_REPLICATED" }],
    reranking_strategy: [{ context: "semantic_search_opt", token: "_s_SS_RERANKING_STRATEGY" }],
    resource: [
        { context: "create_drop_alter", token: "_s_CDA_RESOURCE" },
        { context: "external_type", token: "_s_ET_RESOURCE" },
    ],
    resource_manager_location: [
        { context: "alter_externaldatasource_with", token: "_s_AEDS_RESOURCEMANAGERLOCATION" },
        { context: "create_externaldatasource_with", token: "_s_CEDS_RESOURCEMANAGERLOCATION" },
    ],
    restart: [{ context: "sequence_options", token: "_s_seq_RESTART" }],
    result: [{ context: "after_with_exec_option", token: "_s_AWEO_RESULT" }],
    resumable: [{ context: "ind_options", token: "_s_IO_RESUMABLE" }],
    resume: [{ context: "ind_actions", token: "_s_IA_RESUME" }],
    retention_period: [
        { context: "create_tab_with_data_deletion_opt", token: "_s_DD_RETENTION_PERIOD" },
    ],
    returning: [{ context: "json_func_opt", token: "_s_JFO_RETURNING" }],
    revert: [{ context: "optstmtstarters", token: "_c_REVERT" }],
    role: [
        { context: "alter_server_type", token: "_s_altserv_ROLE" },
        { context: "create_drop_alter", token: "_s_CDA_ROLE" },
    ],
    rollup: [{ context: "optgroupby", token: "_c_ROLLUP" }],
    round_robin: [{ context: "create_externaltable_with", token: "_s_CET_ROUNDROBIN" }],
    route: [{ context: "create_drop_alter", token: "_s_CDA_ROUTE" }],
    row_terminator: [{ context: "create_externalfileformat_with", token: "_s_CEFF_ROWTERMINATOR" }],
    scheduler: [{ context: "pool_affinity_type", token: "_s_paff_SCHED" }],
    schema_name: [{ context: "create_externaltable_with", token: "_s_CET_REMOTESCHEMANAME" }],
    search: [
        { context: "create_drop_alter", token: "_s_CDA_SEARCH" },
        { context: "fulltext_search", token: "_s_FTS_SEARCH" },
    ],
    search_string: [{ context: "semantic_search_opt", token: "_s_SS_SEARCH_STRING" }],
    search_type: [{ context: "semantic_index_col_options", token: "_s_SI_SEARCH_TYPE" }],
    second: [{ context: "create_tab_with_data_deletion_opt", token: "_s_DD_SECOND" }],
    secondary: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_SECONDARY" }],
    secondary_role: [{ context: "ag_replica_option", token: "_s_AG_ROLE_SPECIFIC_OPTION" }],
    secondary_type: [{ context: "geodr_opt", token: "_s_GEODR_SECONDARYTYPE" }],
    security: [{ context: "create_drop_alter", token: "_s_CDA_SECURITY" }],
    security_log: [{ context: "audit_target_type", token: "_s_ET_SECURITY_LOG" }],
    selective: [{ context: "create_drop_alter", token: "_s_CDA_SELECTIVE" }],
    semantic: [{ context: "create_drop_alter", token: "_s_CDA_SEMANTIC" }],
    send: [{ context: "optstmtstarters", token: "_c_SEND" }],
    sensitivity: [
        { context: "add", token: "_s_ADD_SENSITIVITY" },
        { context: "create_drop_alter", token: "_s_CDA_SENSITIVITY" },
    ],
    sequence: [{ context: "create_drop_alter", token: "_s_CDA_SEQUENCE" }],
    sequence_number_column_name: [
        {
            context: "create_table_with_ledger_opt",
            token: "_s_CTWL_LV_SEQUENCE_NUMBER_COLUMN_NAME",
        },
    ],
    serde_method: [{ context: "create_externalfileformat_with", token: "_s_CEFF_SERDEMETHOD" }],
    server: [
        { context: "create_drop_alter", token: "_s_CDA_SERVER" },
        { context: "dump_encryption_opt", token: "_s_DUMPOPT_ENCRYPTION_SERVER" },
        { context: "opteventnotifobjecton", token: "_c_SERVER" },
        { context: "remote_data_archive_opt", token: "_s_REMOTE_DATA_ARCHIVE_DB_OPT_SERVER" },
    ],
    service: [
        { context: "create_drop_alter", token: "_s_CDA_SERVICE" },
        { context: "optdumptypes", token: "_c_SERVICE" },
        { context: "optloadtypes", token: "_c_SERVICE" },
    ],
    service_objective: [{ context: "geodr_opt", token: "_s_GEODR_SRVOBJ" }],
    session: [{ context: "create_drop_alter", token: "_s_CDA_SESSION" }],
    shard_map_manager: [
        { context: "create_externaldatasource_with", token: "_s_CEDS_SHARDMAPMANAGER" },
    ],
    shard_map_name: [
        { context: "alter_externaldatasource_with", token: "_s_AEDS_SHARDMAPNAME" },
        { context: "create_externaldatasource_with", token: "_s_CEDS_SHARDMAPNAME" },
    ],
    sharded: [{ context: "create_externaltable_with", token: "_s_CET_SHARDED" }],
    shared_memory: [{ context: "create_externaldatasource_with", token: "_s_CEDS_SHAREDMEMORY" }],
    sid: [
        { context: "alter_user_with", token: "_s_AUW_SID" },
        { context: "create_user_with", token: "_s_CUW_PROPERTY" },
    ],
    signature: [
        { context: "add", token: "_s_ADD_SIGNATURE" },
        { context: "col_encryption_or_master_key", token: "_s_CEMK_SIGNATURE" },
        { context: "create_drop_alter", token: "_s_CDA_SIGNATURE" },
    ],
    similar_to: [{ context: "vector_search_opt", token: "_s_VS_SIMILAR_TO" }],
    singleton: [{ context: "opt_sxi_path_option", token: "_s_SXI_SINGLETON" }],
    size: [{ context: "semantic_index_col_chunk_options", token: "_s_SIC_SIZE" }],
    size_based_cleanup_mode: [
        { context: "query_store_opt", token: "_s_QDS_SIZE_BASED_CLEANUP_MODE" },
    ],
    snapshot: [{ context: "create_db_type", token: "_s_CREATEDB_SNAP" }],
    softnuma: [{ context: "alter_server_config_set", token: "_s_altserv_config_set_SOFTNUMA" }],
    sorted_data: [{ context: "index_sort_opt", token: "_s_IDXSORTOPT_SORTED_DATA" }],
    sorted_data_reorg: [{ context: "index_sort_opt", token: "_s_IDXSORTOPT_SORTED_DATA_REORG" }],
    source: [
        { context: "external_type", token: "_s_ET_SOURCE" },
        { context: "gen_chunks_opt", token: "_s_GC_SOURCE" },
    ],
    sparse: [
        { context: "col_add_drop_opt", token: "_s_COLADDROPOPT_SPARSE" },
        { context: "col_def_opt", token: "_s_COLDEFOPT_SPARSE" },
        { context: "opt_storage_id", token: "_s_OSI_SPARSE" },
    ],
    spatial: [{ context: "create_drop_alter", token: "_s_CDA_SPATIAL" }],
    sql: [{ context: "opt_sxi_path_kind", token: "_s_SXI_SQL" }],
    stale_page_detection: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_STALE_PAGE_DETECTION" }],
    start: [{ context: "sequence_options", token: "_s_seq_START" }],
    start_id: [{ context: "vector_search_opt", token: "_s_VS_START_ID" }],
    statistics_only: [{ context: "ind_options", token: "_s_IO_STATSONLY" }],
    stoplist: [{ context: "fulltext_search", token: "_s_FTS_STOPLIST" }],
    store: [{ context: "view_snapshot", token: "_s_SSTORE" }],
    stream: [{ context: "external_type", token: "_s_ET_STREAM" }],
    string_delimiter: [
        { context: "create_externalfileformat_with", token: "_s_CEFF_STRINGDELIMITER" },
    ],
    switch: [{ context: "alttab_actions", token: "_s_ALTTAB_SWITCH" }],
    symmetric: [
        { context: "create_drop_alter", token: "_s_CDA_SYMMETRIC" },
        { context: "optopenclosetypes", token: "_c_SYMMETRIC" },
    ],
    synonym: [{ context: "create_drop_alter", token: "_s_CDA_SYNONYM" }],
    system_versioning: [
        { context: "create_tab_with_opt", token: "_s_CTW_SYSTEM_VERSIONING" },
        { context: "tab_opt_name", token: "_s_TABOPTNAME_SYSTEM_VERSIONING" },
    ],
    table: [{ context: "external_type", token: "_s_ET_TABLE" }],
    target: [{ context: "create_drop_alter", token: "_s_CDA_TARGET" }],
    target_recovery_time: [{ context: "alter_db_opt", token: "_s_ALTDBOPT_RECOVERY" }],
    temporal_history_retention: [
        { context: "alter_db_opt", token: "_s_ALTDBOPT_TEMPORAL_RETENTION" },
    ],
    textimage_on: [{ context: "create_tab_opt", token: "_s_CTO_TEXTIMAGE_ON" }],
    throw: [{ context: "optstmtstarters", token: "_c_THROW" }],
    top_n: [
        { context: "semantic_search_opt", token: "_s_SS_TOP_N" },
        { context: "vector_search_opt", token: "_s_VS_TOP_N" },
    ],
    transaction_id_column_name: [
        { context: "create_table_with_ledger_opt", token: "_s_CTWL_LV_TRANSACTION_ID_COLUMN_NAME" },
    ],
    true: [{ context: "create_externalfileformat_with", token: "_s_CEFF_TRUE" }],
    try: [{ context: "after_end", token: "_s_AE_TRY" }],
    type: [
        { context: "create_drop_alter", token: "_s_CDA_TYPE" },
        { context: "create_externaldatasource_with", token: "_s_CEDS_TYPE" },
        { context: "create_user_with", token: "_s_CUW_USER_TYPE" },
        { context: "ind_options", token: "_s_IO_VECTORINDEXTYPE" },
        { context: "opteventnotifobjecton", token: "_c_TYPE" },
        { context: "semantic_index_col_chunk_options", token: "_s_SIC_TYPE" },
        { context: "semantic_index_col_options", token: "_s_SI_TYPE" },
    ],
    unbounded: [{ context: "over_clause", token: "_s_UNBOUNDED" }],
    url: [
        { context: "audit_target_type", token: "_s_ET_URL" },
        { context: "external_type", token: "_s_ET_URLFORMAT" },
    ],
    use_type_default: [
        { context: "create_externalfileformat_with", token: "_s_CEFF_USETYPEDEFAULT" },
    ],
    user_db: [{ context: "create_table_with_location_opt", token: "_s_CTWL_USERDB" }],
    value: [
        { context: "col_encryption_or_master_key", token: "_s_CEMK_VALUE" },
        { context: "create_externaltable_with", token: "_s_CET_VALUE" },
    ],
    vector: [{ context: "create_drop_alter", token: "_s_CDA_VECTOR" }],
    vector_index: [{ context: "semantic_index_with_options", token: "_s_SIW_VECTOR_INDEX" }],
    wait_at_low_priority: [{ context: "ind_options", token: "_s_IO_WAIT_AT_LOW_PRIORITY" }],
    week: [{ context: "create_tab_with_data_deletion_opt", token: "_s_DD_WEEK" }],
    weight: [{ context: "semantic_search_opt", token: "_s_SS_WEIGHT" }],
    workload: [{ context: "create_drop_alter", token: "_s_CDA_WORKLOAD" }],
    workload_group: [{ context: "db_encryption_opt", token: "_s_ENCRYPTION_RESOURCE_GOVERNOR" }],
    xml: [{ context: "create_drop_alter", token: "_s_CDA_XML" }],
    xmlnamespaces: [{ context: "after_with", token: "_s_AW_XMLNAMESPACES" }],
    xquery: [{ context: "opt_sxi_path_kind", token: "_s_SXI_XQUERY" }],
    year: [{ context: "create_tab_with_data_deletion_opt", token: "_s_DD_YEAR" }],
} satisfies Readonly<Record<string, readonly ContextualKeywordUse[]>>);

export const reservedKeywordNames = Object.freeze(Object.keys(reservedKeywordMetadata));
export const contextualKeywordNames = Object.freeze(Object.keys(contextualKeywordMetadata));

const reservedKeywordSet = new Set<string>(reservedKeywordNames);
const contextualKeywordSet = new Set<string>(contextualKeywordNames);

export function keywordMetadata(
    text: string,
):
    | { readonly category: "reserved"; readonly minimumCompatibility: number }
    | { readonly category: "contextual"; readonly contexts: readonly ContextualKeywordUse[] }
    | undefined {
    const normalized = text.toLowerCase();
    const reserved = reservedKeywordMetadata[normalized as keyof typeof reservedKeywordMetadata];
    if (reserved) {
        return { category: "reserved", minimumCompatibility: reserved.minimumCompatibility };
    }
    const contextual =
        contextualKeywordMetadata[normalized as keyof typeof contextualKeywordMetadata];
    return contextual ? { category: "contextual", contexts: contextual } : undefined;
}

export function isReservedKeyword(text: string): boolean {
    return reservedKeywordSet.has(text.toLowerCase());
}

export function isContextualKeyword(text: string): boolean {
    return contextualKeywordSet.has(text.toLowerCase());
}

export function isTsqlKeyword(text: string): boolean {
    const normalized = text.toLowerCase();
    return reservedKeywordSet.has(normalized) || contextualKeywordSet.has(normalized);
}
