name: Build Data Workspace Extension
description: Builds the Data Workspace VS Code extension.
runs:
  using: "composite"
  steps:
    - name: DataWorkspace - Build extension
      shell: bash
      run: |
        npm run build -- --target data-workspace
